// Exact Cosmetic Data from User Account JSON
export const ALL_NEON_REWARDS: string[] = [
  "unlock_neon_animated_1",
  "unlock_neon_animated_2",
  "unlock_neon_animated_3",
  "unlock_neon_animated_4",
  "unlock_neon_animated_5",
  "unlock_neon_animated_6",
  "unlock_neon_animated_7",
  "unlock_neon_animated_8",
  "unlock_neon_animated_9",
  "unlock_neon_animated_10",
  "unlock_neon_animated_11",
  "unlock_neon_animated_12",
  "unlock_neon_animated_13",
  "unlock_neon_animated_14",
  "unlock_neon_animated_15"
];
export const ALL_NEON_BODY_PARTS: string[] = [
  "neon_front_static",
  "neon_side_static",
  "neon_rear_static",
  "neon_front_empty",
  "neon_side_empty",
  "neon_rear_empty",
  "neon_front_animated",
  "neon_side_animated",
  "neon_rear_animated",
  "neon_front_animated_1",
  "neon_front_animated_2",
  "neon_front_animated_3",
  "neon_front_animated_4",
  "neon_front_animated_5",
  "neon_front_animated_6",
  "neon_front_animated_7",
  "neon_front_animated_8",
  "neon_front_animated_9",
  "neon_front_animated_10",
  "neon_front_animated_11",
  "neon_front_animated_12",
  "neon_front_animated_13",
  "neon_front_animated_14",
  "neon_front_animated_15",
  "neon_side_animated_1",
  "neon_side_animated_2",
  "neon_side_animated_3",
  "neon_side_animated_4",
  "neon_side_animated_5",
  "neon_side_animated_6",
  "neon_side_animated_7",
  "neon_side_animated_8",
  "neon_side_animated_9",
  "neon_side_animated_10",
  "neon_side_animated_11",
  "neon_side_animated_12",
  "neon_side_animated_13",
  "neon_side_animated_14",
  "neon_side_animated_15",
  "neon_rear_animated_1",
  "neon_rear_animated_2",
  "neon_rear_animated_3",
  "neon_rear_animated_4",
  "neon_rear_animated_5",
  "neon_rear_animated_6",
  "neon_rear_animated_7",
  "neon_rear_animated_8",
  "neon_rear_animated_9",
  "neon_rear_animated_10",
  "neon_rear_animated_11",
  "neon_rear_animated_12",
  "neon_rear_animated_13",
  "neon_rear_animated_14",
  "neon_rear_animated_15",
  "neon_animated_1",
  "neon_animated_2",
  "neon_animated_3",
  "neon_animated_4",
  "neon_animated_5",
  "neon_animated_6",
  "neon_animated_7",
  "neon_animated_8",
  "neon_animated_9",
  "neon_animated_10",
  "neon_animated_11",
  "neon_animated_12",
  "neon_animated_13",
  "neon_animated_14",
  "neon_animated_15"
];

export const ALL_TIRE_SIDE_WALL_REWARDS: string[] = [
  "unlock_tire_side_wall_1",
  "unlock_tire_side_wall_2",
  "unlock_tire_side_wall_3",
  "unlock_tire_side_wall_4",
  "unlock_tire_side_wall_6",
  "unlock_tire_side_wall_7",
  "unlock_tire_side_wall_8",
  "unlock_tire_side_wall_9",
  "unlock_tire_side_wall_10",
  "unlock_tire_side_wall_11",
  "unlock_tire_side_wall_12",
  "unlock_tire_side_wall_13",
  "unlock_tire_side_wall_14",
  "unlock_tire_side_wall_faster_5"
];
export const ALL_TIRE_SIDE_WALL_BODY_PARTS: string[] = [
  "tire_side_wall_apex_rubber",
  "tire_side_wall_blank",
  "tire_side_wall_donuts",
  "tire_side_wall_drifthunters",
  "tire_side_wall_faster",
  "tire_side_wall_faster_white",
  "tire_side_wall_gripx",
  "tire_side_wall_oversteer_1",
  "tire_side_wall_oversteer_2",
  "tire_side_wall_oversteer_3",
  "tire_side_wall_shinobi",
  "tire_side_wall_toccata",
  "tire_side_wall_yolotire",
  "tire_side_wall_yolotire_yelow"
];

export const ALL_PROFILE_STYLE_REWARDS: string[] = [
  "unlock_avatar_1",
  "unlock_avatar_2",
  "unlock_avatar_3",
  "unlock_avatar_4",
  "unlock_avatar_5",
  "unlock_avatar_6",
  "unlock_avatar_7",
  "unlock_avatar_8",
  "unlock_avatar_9",
  "unlock_avatar_10",
  "unlock_avatar_11",
  "unlock_avatar_12",
  "unlock_avatar_13",
  "unlock_avatar_14",
  "unlock_avatar_15",
  "unlock_avatar_16",
  "unlock_avatar_17",
  "unlock_avatar_18",
  "unlock_banner_1",
  "unlock_banner_2",
  "unlock_banner_3",
  "unlock_banner_4",
  "unlock_banner_5",
  "unlock_banner_6",
  "unlock_banner_7",
  "unlock_banner_8",
  "unlock_banner_9",
  "unlock_banner_10",
  "unlock_banner_11",
  "unlock_banner_12",
  "unlock_banner_13",
  "unlock_banner_14",
  "unlock_banner_15",
  "unlock_banner_16",
  "unlock_banner_17",
  "unlock_banner_18",
  "unlock_frame_1",
  "unlock_frame_2",
  "unlock_frame_3",
  "unlock_frame_4",
  "unlock_frame_5",
  "unlock_frame_6",
  "unlock_frame_7",
  "unlock_frame_8",
  "unlock_frame_9",
  "unlock_frame_10",
  "unlock_frame_11",
  "unlock_frame_12",
  "unlock_frame_13",
  "unlock_frame_14",
  "unlock_frame_15",
  "unlock_frame_16",
  "unlock_frame_17",
  "unlock_frame_18"
];
export const EXTENDED_ORDERED_COSMETIC_SETS = [
  {
    "id": 1,
    "avatar": "avatar_1",
    "frame": "frame_1",
    "banner": "banner_1",
    "unlock_avatar": "unlock_avatar_1",
    "unlock_frame": "unlock_frame_1",
    "unlock_banner": "unlock_banner_1",
    "label": "Set 1"
  },
  {
    "id": 2,
    "avatar": "avatar_2",
    "frame": "frame_2",
    "banner": "banner_2",
    "unlock_avatar": "unlock_avatar_2",
    "unlock_frame": "unlock_frame_2",
    "unlock_banner": "unlock_banner_2",
    "label": "Set 2"
  },
  {
    "id": 3,
    "avatar": "avatar_3",
    "frame": "frame_3",
    "banner": "banner_3",
    "unlock_avatar": "unlock_avatar_3",
    "unlock_frame": "unlock_frame_3",
    "unlock_banner": "unlock_banner_3",
    "label": "Set 3"
  },
  {
    "id": 4,
    "avatar": "avatar_4",
    "frame": "frame_4",
    "banner": "banner_4",
    "unlock_avatar": "unlock_avatar_4",
    "unlock_frame": "unlock_frame_4",
    "unlock_banner": "unlock_banner_4",
    "label": "Set 4"
  },
  {
    "id": 5,
    "avatar": "avatar_5",
    "frame": "frame_5",
    "banner": "banner_5",
    "unlock_avatar": "unlock_avatar_5",
    "unlock_frame": "unlock_frame_5",
    "unlock_banner": "unlock_banner_5",
    "label": "Set 5"
  },
  {
    "id": 6,
    "avatar": "avatar_6",
    "frame": "frame_6",
    "banner": "banner_6",
    "unlock_avatar": "unlock_avatar_6",
    "unlock_frame": "unlock_frame_6",
    "unlock_banner": "unlock_banner_6",
    "label": "Set 6"
  },
  {
    "id": 7,
    "avatar": "avatar_7",
    "frame": "frame_7",
    "banner": "banner_7",
    "unlock_avatar": "unlock_avatar_7",
    "unlock_frame": "unlock_frame_7",
    "unlock_banner": "unlock_banner_7",
    "label": "Set 7"
  },
  {
    "id": 8,
    "avatar": "avatar_8",
    "frame": "frame_8",
    "banner": "banner_8",
    "unlock_avatar": "unlock_avatar_8",
    "unlock_frame": "unlock_frame_8",
    "unlock_banner": "unlock_banner_8",
    "label": "Set 8"
  },
  {
    "id": 9,
    "avatar": "avatar_9",
    "frame": "frame_9",
    "banner": "banner_9",
    "unlock_avatar": "unlock_avatar_9",
    "unlock_frame": "unlock_frame_9",
    "unlock_banner": "unlock_banner_9",
    "label": "Set 9"
  },
  {
    "id": 10,
    "avatar": "avatar_10",
    "frame": "frame_10",
    "banner": "banner_10",
    "unlock_avatar": "unlock_avatar_10",
    "unlock_frame": "unlock_frame_10",
    "unlock_banner": "unlock_banner_10",
    "label": "Set 10"
  },
  {
    "id": 11,
    "avatar": "avatar_11",
    "frame": "frame_11",
    "banner": "banner_11",
    "unlock_avatar": "unlock_avatar_11",
    "unlock_frame": "unlock_frame_11",
    "unlock_banner": "unlock_banner_11",
    "label": "Set 11"
  },
  {
    "id": 12,
    "avatar": "avatar_12",
    "frame": "frame_12",
    "banner": "banner_12",
    "unlock_avatar": "unlock_avatar_12",
    "unlock_frame": "unlock_frame_12",
    "unlock_banner": "unlock_banner_12",
    "label": "Set 12"
  },
  {
    "id": 13,
    "avatar": "avatar_13",
    "frame": "frame_13",
    "banner": "banner_13",
    "unlock_avatar": "unlock_avatar_13",
    "unlock_frame": "unlock_frame_13",
    "unlock_banner": "unlock_banner_13",
    "label": "Set 13"
  },
  {
    "id": 14,
    "avatar": "avatar_14",
    "frame": "frame_14",
    "banner": "banner_14",
    "unlock_avatar": "unlock_avatar_14",
    "unlock_frame": "unlock_frame_14",
    "unlock_banner": "unlock_banner_14",
    "label": "Set 14"
  },
  {
    "id": 15,
    "avatar": "avatar_15",
    "frame": "frame_15",
    "banner": "banner_15",
    "unlock_avatar": "unlock_avatar_15",
    "unlock_frame": "unlock_frame_15",
    "unlock_banner": "unlock_banner_15",
    "label": "Set 15"
  },
  {
    "id": 16,
    "avatar": "avatar_16",
    "frame": "frame_16",
    "banner": "banner_16",
    "unlock_avatar": "unlock_avatar_16",
    "unlock_frame": "unlock_frame_16",
    "unlock_banner": "unlock_banner_16",
    "label": "Set 16"
  },
  {
    "id": 17,
    "avatar": "avatar_17",
    "frame": "frame_17",
    "banner": "banner_17",
    "unlock_avatar": "unlock_avatar_17",
    "unlock_frame": "unlock_frame_17",
    "unlock_banner": "unlock_banner_17",
    "label": "Set 17"
  },
  {
    "id": 18,
    "avatar": "avatar_18",
    "frame": "frame_18",
    "banner": "banner_18",
    "unlock_avatar": "unlock_avatar_18",
    "unlock_frame": "unlock_frame_18",
    "unlock_banner": "unlock_banner_18",
    "label": "Set 18"
  },
  {
    "id": 19,
    "avatar": "avatar_champion_1",
    "frame": "frame_champion_1",
    "banner": "banner_champion_1",
    "unlock_avatar": "unlock_avatar_champion_1",
    "unlock_frame": "unlock_frame_champion_1",
    "unlock_banner": "unlock_banner_champion_1",
    "label": "Champion 1"
  },
  {
    "id": 20,
    "avatar": "avatar_champion_2",
    "frame": "frame_champion_2",
    "banner": "banner_champion_2",
    "unlock_avatar": "unlock_avatar_champion_2",
    "unlock_frame": "unlock_frame_champion_2",
    "unlock_banner": "unlock_banner_champion_2",
    "label": "Champion 2"
  },
  {
    "id": 21,
    "avatar": "avatar_champion_3",
    "frame": "frame_champion_3",
    "banner": "banner_champion_3",
    "unlock_avatar": "unlock_avatar_champion_3",
    "unlock_frame": "unlock_frame_champion_3",
    "unlock_banner": "unlock_banner_champion_3",
    "label": "Champion 3"
  },
  {
    "id": 22,
    "avatar": "avatar_champion_4",
    "frame": "frame_champion_4",
    "banner": "banner_champion_4",
    "unlock_avatar": "unlock_avatar_champion_4",
    "unlock_frame": "unlock_frame_champion_4",
    "unlock_banner": "unlock_banner_champion_4",
    "label": "Champion 4"
  }
];

export const ALL_NUMBER_PLATE_REWARDS: string[] = [
  "unlock_numberplate_lunarcarnival_gold",
  "unlock_numberplate_lunarcarnival_white",
  "unlock_numberplate_confrontation_skull",
  "unlock_numberplate_confrontation_flame",
  "unlock_number_plate_sunset_city_black",
  "unlock_number_plate_street_500_black",
  "unlock_number_plate_akuma_gold",
  "unlock_number_plate_rock",
  "unlock_number_plate_stock",
  "unlock_number_plate_ufo",
  "unlock_number_plate_oni_gold",
  "unlock_number_plate_gymkhana_fest_1_logo",
  "unlock_number_plate_gymkhana_fest_2_steelpace",
  "unlock_number_plate_gymkhana_fest_1_number_2",
  "unlock_number_plate_gymkhana_fest_1_number_1",
  "unlock_number_plate_eternal_black",
  "unlock_number_plate_akuma_black",
  "unlock_number_plate_street_500_white",
  "unlock_number_plate_gymkhana_fest_2_13racing",
  "unlock_number_plate_gymkhana_fest_2_show",
  "unlock_number_plate_2fast4u",
  "unlock_number_plate_dr-ft",
  "unlock_number_plate_halloween_2_zmbie",
  "unlock_number_plate_halloween_2_w1tch",
  "unlock_number_plate_halloween_2_h3llcar",
  "unlock_number_plate_p1zz4",
  "unlock_number_plate_no1se",
  "unlock_number_plate_h07dog",
  "unlock_number_plate_gr4ng3",
  "unlock_number_plate_donut",
  "unlock_number_plate_cla55ic",
  "unlock_number_plate_blankcat",
  "unlock_number_plate_5u5h1",
  "unlock_number_plate_upgrad3",
  "unlock_number_plate_top-t13r",
  "unlock_number_plate_t3am13",
  "unlock_number_plate_s1mpl3",
  "unlock_number_plate_patrol_dep",
  "unlock_number_plate_own3d",
  "unlock_number_plate_npc",
  "unlock_number_plate_m4y4",
  "unlock_number_plate_et82ufo",
  "unlock_number_plate_et82city",
  "unlock_number_plate_b-005t",
  "unlock_number_plate_al13n",
  "unlock_number_plate_666666",
  "unlock_number_plate_456897",
  "unlock_number_plate_500hp",
  "unlock_number_plate_5tock",
  "unlock_number_plate_4zt3c",
  "unlock_number_plate_brnrubr",
  "unlock_number_plate_kawa11",
  "unlock_number_plate_empty",
  "unlock_number_plate_oni_graffiti",
  "unlock_number_plate_snowfest_winter",
  "unlock_number_plate_snowfest_ny26",
  "unlock_number_plate_snowfest_gift26",
  "unlock_number_plate_no_noise_just_pace_team",
  "unlock_number_plate_i_dont",
  "unlock_number_plate_0000",
  "unlock_number_plate_serafim_xplpr",
  "unlock_number_plate_serafim_l1fexp",
  "unlock_number_plate_serafim_g4m3r",
  "unlock_number_plate_final_charge_flame",
  "unlock_number_plate_final_charge_fire26",
  "unlock_number_plate_final_charge_bless",
  "unlock_number_plate_st756",
  "unlock_number_plate_run",
  "unlock_number_plate_championship_fs2026",
  "unlock_number_plate_championship_redcrd",
  "unlock_number_plate_championship_goal7",
  "unlock_numberplate_gymkhana_fest_1_Logo",
  "unlock_numberplate_gymkhana_fest_1_number_1",
  "unlock_numberplate_gymkhana_fest_1_number_2"
];
export const ALL_NUMBER_PLATE_BODY_PARTS: string[] = [
  "number_plate_stock",
  "number_plate_0000",
  "number_plate_2fast4u",
  "number_plate_456897",
  "number_plate_4zt3c",
  "number_plate_500hp",
  "number_plate_5tock",
  "number_plate_5u5h1",
  "number_plate_666666",
  "number_plate_akuma_black",
  "number_plate_akuma_gold",
  "number_plate_al13n",
  "number_plate_b-005t",
  "number_plate_blankcat",
  "number_plate_brnrubr",
  "number_plate_championship_fs2026",
  "number_plate_championship_goal7",
  "number_plate_championship_redcrd",
  "number_plate_cla55ic",
  "number_plate_confrontation_flame",
  "number_plate_confrontation_skull",
  "number_plate_donut",
  "number_plate_dr-ft",
  "number_plate_et82city",
  "number_plate_et82ufo",
  "number_plate_eternal_black",
  "number_plate_final_charge_bless",
  "number_plate_final_charge_fire26",
  "number_plate_final_charge_flame",
  "number_plate_gr4ng3",
  "number_plate_gymkhana_fest_1_logo",
  "number_plate_gymkhana_fest_1_number_1",
  "number_plate_gymkhana_fest_1_number_2",
  "number_plate_gymkhana_fest_2_13racing",
  "number_plate_gymkhana_fest_2_show",
  "number_plate_gymkhana_fest_2_steelpace",
  "number_plate_h07dog",
  "number_plate_halloween_2_h3llcar",
  "number_plate_halloween_2_w1tch",
  "number_plate_halloween_2_zmbie",
  "number_plate_i_dont",
  "number_plate_kawa11",
  "number_plate_lunarcarnival_gold",
  "number_plate_lunarcarnival_white",
  "number_plate_m4y4",
  "number_plate_no1se",
  "number_plate_no_noise_just_pace_team",
  "number_plate_npc",
  "number_plate_oni_gold",
  "number_plate_oni_graffiti",
  "number_plate_own3d",
  "number_plate_p1zz4",
  "number_plate_patrol_dep",
  "number_plate_run",
  "number_plate_s1mpl3",
  "number_plate_serafim_g4m3r",
  "number_plate_serafim_l1fexp",
  "number_plate_serafim_xplpr",
  "number_plate_snowfest_gift26",
  "number_plate_snowfest_ny26",
  "number_plate_snowfest_winter",
  "number_plate_st756",
  "number_plate_street_500_black",
  "number_plate_street_500_white",
  "number_plate_sunset_city_black",
  "number_plate_t3am13",
  "number_plate_top-t13r",
  "number_plate_ufo",
  "number_plate_upgrad3"
];

export const ALL_WHEEL_RIM_REWARDS: string[] = [
  "unlock_wheel_rim_1379",
  "unlock_wheel_rim_1380",
  "unlock_wheel_rim_1381",
  "unlock_wheel_rim_1382",
  "unlock_wheel_rim_1383",
  "unlock_wheel_rim_1384",
  "unlock_wheel_rim_1385",
  "unlock_wheel_rim_1386",
  "unlock_wheel_rim_1387",
  "unlock_wheel_rim_1388",
  "unlock_wheel_rim_1389",
  "unlock_wheel_rim_1390",
  "unlock_wheel_rim_1391",
  "unlock_wheel_rim_1392",
  "unlock_wheel_rim_1393",
  "unlock_wheel_rim_1394",
  "unlock_wheel_rim_1395",
  "unlock_wheel_rim_1396",
  "unlock_wheel_rim_1397",
  "unlock_wheel_rim_1398",
  "unlock_wheel_rim_1399",
  "unlock_wheel_rim_1400",
  "unlock_wheel_rim_1401",
  "unlock_wheel_rim_1402",
  "unlock_wheel_rim_1403",
  "unlock_wheel_rim_1404",
  "unlock_wheel_rim_1405",
  "unlock_wheel_rim_1406",
  "unlock_wheel_rim_1407",
  "unlock_wheel_rim_1408",
  "unlock_wheel_rim_1409",
  "unlock_wheel_rim_1410",
  "unlock_wheel_rim_1411",
  "unlock_wheel_rim_1412",
  "unlock_wheel_rim_1413",
  "unlock_wheel_rim_1414",
  "unlock_wheel_rim_1415",
  "unlock_wheel_rim_1416",
  "unlock_wheel_rim_1417",
  "unlock_wheel_rim_1418",
  "unlock_wheel_rim_1419",
  "unlock_wheel_rim_1420",
  "unlock_wheel_rim_1421",
  "unlock_wheel_rim_1422",
  "unlock_wheel_rim_1423",
  "unlock_wheel_rim_1424",
  "unlock_wheel_rim_1425",
  "unlock_wheel_rim_1426",
  "unlock_wheel_rim_1427",
  "unlock_wheel_rim_1428",
  "unlock_wheel_rim_1429",
  "unlock_wheel_rim_1430",
  "unlock_wheel_rim_1431",
  "unlock_wheel_rim_1432",
  "unlock_wheel_rim_1433",
  "unlock_wheel_rim_1434",
  "unlock_wheel_rim_1435",
  "unlock_wheel_rim_1436",
  "unlock_wheel_rim_1438",
  "unlock_wheel_rim_1439",
  "unlock_wheel_rim_1440",
  "unlock_wheel_rim_1441",
  "unlock_wheel_rim_1442",
  "unlock_wheel_rim_1443",
  "unlock_wheel_rim_1444",
  "unlock_wheel_rim_1445",
  "unlock_wheel_rim_1446",
  "unlock_wheel_rim_1447",
  "unlock_wheel_rim_1448",
  "unlock_wheel_rim_1449",
  "unlock_wheel_rim_1450",
  "unlock_wheel_rim_1451",
  "unlock_wheel_rim_1452",
  "unlock_wheel_rim_1453",
  "unlock_wheel_rim_1454",
  "unlock_wheel_rim_1455",
  "unlock_wheel_rim_1456",
  "unlock_wheel_rim_1457",
  "unlock_wheel_rim_1458",
  "unlock_wheel_rim_1459",
  "unlock_wheel_rim_1460",
  "unlock_wheel_rim_1461",
  "unlock_wheel_rim_1462",
  "unlock_wheel_rim_1463",
  "unlock_wheel_rim_1464",
  "unlock_wheel_rim_1465",
  "unlock_wheel_rim_1474",
  "unlock_wheel_rim_1475",
  "unlock_wheel_rim_1476",
  "unlock_wheel_rim_1477",
  "unlock_wheel_rim_1478",
  "unlock_wheel_rim_1479",
  "unlock_wheel_rim_1482",
  "unlock_wheel_rim_1483",
  "unlock_wheel_rim_1484",
  "unlock_wheel_rim_1485",
  "unlock_wheel_rim_1486",
  "unlock_wheel_rim_1489",
  "unlock_wheel_rim_1490",
  "unlock_wheel_rim_1491",
  "unlock_wheel_rim_1492",
  "unlock_wheel_rim_1493",
  "unlock_wheel_rim_1494",
  "unlock_wheel_rim_1499",
  "unlock_wheel_rim_1500",
  "unlock_wheel_rim_1501",
  "unlock_wheel_rim_1502",
  "unlock_wheel_rim_1503",
  "unlock_wheel_rim_1504",
  "unlock_wheel_rim_14841"
];
export const ALL_WHEEL_RIM_BODY_PARTS: string[] = [
  "wheel_rim_446",
  "wheel_rim_412",
  "wheel_rim_1",
  "wheel_rim_2",
  "wheel_rim_3",
  "wheel_rim_4",
  "wheel_rim_5",
  "wheel_rim_6",
  "wheel_rim_7",
  "wheel_rim_8",
  "wheel_rim_9",
  "wheel_rim_10",
  "wheel_rim_11",
  "wheel_rim_12",
  "wheel_rim_13",
  "wheel_rim_14",
  "wheel_rim_15",
  "wheel_rim_16",
  "wheel_rim_17",
  "wheel_rim_18",
  "wheel_rim_19",
  "wheel_rim_20",
  "wheel_rim_21",
  "wheel_rim_22",
  "wheel_rim_23",
  "wheel_rim_24",
  "wheel_rim_25",
  "wheel_rim_26",
  "wheel_rim_27",
  "wheel_rim_28",
  "wheel_rim_29",
  "wheel_rim_30",
  "wheel_rim_31",
  "wheel_rim_32",
  "wheel_rim_33",
  "wheel_rim_34",
  "wheel_rim_35",
  "wheel_rim_36",
  "wheel_rim_37",
  "wheel_rim_38",
  "wheel_rim_39",
  "wheel_rim_40",
  "wheel_rim_41",
  "wheel_rim_42",
  "wheel_rim_43",
  "wheel_rim_44",
  "wheel_rim_45",
  "wheel_rim_46",
  "wheel_rim_47",
  "wheel_rim_48",
  "wheel_rim_49",
  "wheel_rim_50",
  "wheel_rim_51",
  "wheel_rim_52",
  "wheel_rim_53",
  "wheel_rim_54",
  "wheel_rim_55",
  "wheel_rim_56",
  "wheel_rim_57",
  "wheel_rim_58",
  "wheel_rim_59",
  "wheel_rim_60",
  "wheel_rim_61",
  "wheel_rim_62",
  "wheel_rim_63",
  "wheel_rim_64",
  "wheel_rim_65",
  "wheel_rim_66",
  "wheel_rim_67",
  "wheel_rim_68",
  "wheel_rim_69",
  "wheel_rim_70",
  "wheel_rim_71",
  "wheel_rim_72",
  "wheel_rim_73",
  "wheel_rim_74",
  "wheel_rim_75",
  "wheel_rim_76",
  "wheel_rim_77",
  "wheel_rim_78",
  "wheel_rim_79",
  "wheel_rim_183",
  "wheel_rim_184",
  "wheel_rim_360",
  "wheel_rim_361",
  "wheel_rim_362",
  "wheel_rim_363",
  "wheel_rim_364",
  "wheel_rim_365",
  "wheel_rim_366",
  "wheel_rim_367",
  "wheel_rim_368",
  "wheel_rim_369",
  "wheel_rim_370",
  "wheel_rim_371",
  "wheel_rim_372",
  "wheel_rim_373",
  "wheel_rim_374",
  "wheel_rim_375",
  "wheel_rim_376",
  "wheel_rim_377",
  "wheel_rim_378",
  "wheel_rim_379",
  "wheel_rim_380",
  "wheel_rim_381",
  "wheel_rim_382",
  "wheel_rim_383",
  "wheel_rim_384",
  "wheel_rim_385",
  "wheel_rim_386",
  "wheel_rim_387",
  "wheel_rim_388",
  "wheel_rim_389",
  "wheel_rim_390",
  "wheel_rim_391",
  "wheel_rim_392",
  "wheel_rim_393",
  "wheel_rim_394",
  "wheel_rim_395",
  "wheel_rim_396",
  "wheel_rim_397",
  "wheel_rim_398",
  "wheel_rim_399",
  "wheel_rim_400",
  "wheel_rim_401",
  "wheel_rim_402",
  "wheel_rim_403",
  "wheel_rim_404",
  "wheel_rim_405",
  "wheel_rim_406",
  "wheel_rim_407",
  "wheel_rim_408",
  "wheel_rim_409",
  "wheel_rim_410",
  "wheel_rim_411",
  "wheel_rim_413",
  "wheel_rim_414",
  "wheel_rim_415",
  "wheel_rim_416",
  "wheel_rim_417",
  "wheel_rim_418",
  "wheel_rim_419",
  "wheel_rim_420",
  "wheel_rim_421",
  "wheel_rim_422",
  "wheel_rim_423",
  "wheel_rim_424",
  "wheel_rim_425",
  "wheel_rim_426",
  "wheel_rim_427",
  "wheel_rim_428",
  "wheel_rim_429",
  "wheel_rim_430",
  "wheel_rim_431",
  "wheel_rim_432",
  "wheel_rim_433",
  "wheel_rim_434",
  "wheel_rim_435",
  "wheel_rim_436",
  "wheel_rim_437",
  "wheel_rim_438",
  "wheel_rim_439",
  "wheel_rim_440",
  "wheel_rim_441",
  "wheel_rim_442",
  "wheel_rim_443",
  "wheel_rim_444",
  "wheel_rim_445",
  "wheel_rim_447",
  "wheel_rim_448",
  "wheel_rim_449",
  "wheel_rim_450",
  "wheel_rim_451",
  "wheel_rim_452",
  "wheel_rim_453",
  "wheel_rim_454",
  "wheel_rim_455",
  "wheel_rim_456",
  "wheel_rim_457",
  "wheel_rim_458",
  "wheel_rim_459",
  "wheel_rim_460",
  "wheel_rim_461",
  "wheel_rim_462",
  "wheel_rim_463",
  "wheel_rim_464",
  "wheel_rim_465",
  "wheel_rim_466",
  "wheel_rim_467",
  "wheel_rim_468",
  "wheel_rim_469",
  "wheel_rim_470",
  "wheel_rim_700",
  "wheel_rim_701",
  "wheel_rim_702",
  "wheel_rim_703",
  "wheel_rim_704",
  "wheel_rim_705",
  "wheel_rim_706",
  "wheel_rim_707",
  "wheel_rim_708",
  "wheel_rim_709",
  "wheel_rim_710",
  "wheel_rim_1283",
  "wheel_rim_1285",
  "wheel_rim_1286",
  "wheel_rim_1287",
  "wheel_rim_1288",
  "wheel_rim_1289",
  "wheel_rim_1290",
  "wheel_rim_1291",
  "wheel_rim_1292",
  "wheel_rim_1293",
  "wheel_rim_1294",
  "wheel_rim_1295",
  "wheel_rim_1296",
  "wheel_rim_1297",
  "wheel_rim_1298",
  "wheel_rim_1299",
  "wheel_rim_1300",
  "wheel_rim_1301",
  "wheel_rim_1302",
  "wheel_rim_1303",
  "wheel_rim_1304",
  "wheel_rim_1305",
  "wheel_rim_1306",
  "wheel_rim_1307",
  "wheel_rim_1308",
  "wheel_rim_1309",
  "wheel_rim_1310",
  "wheel_rim_1311",
  "wheel_rim_1312",
  "wheel_rim_1313",
  "wheel_rim_1314",
  "wheel_rim_1315",
  "wheel_rim_1316",
  "wheel_rim_1317",
  "wheel_rim_1318",
  "wheel_rim_1319",
  "wheel_rim_1320",
  "wheel_rim_1321",
  "wheel_rim_1322",
  "wheel_rim_1323",
  "wheel_rim_1324",
  "wheel_rim_1325",
  "wheel_rim_1326",
  "wheel_rim_1327",
  "wheel_rim_1328",
  "wheel_rim_1329",
  "wheel_rim_1330",
  "wheel_rim_1331",
  "wheel_rim_1332",
  "wheel_rim_1333",
  "wheel_rim_1334",
  "wheel_rim_1335",
  "wheel_rim_1336",
  "wheel_rim_1337",
  "wheel_rim_1338",
  "wheel_rim_1339",
  "wheel_rim_1340",
  "wheel_rim_1341",
  "wheel_rim_1342",
  "wheel_rim_1343",
  "wheel_rim_1344",
  "wheel_rim_1345",
  "wheel_rim_1346",
  "wheel_rim_1347",
  "wheel_rim_1348",
  "wheel_rim_1349",
  "wheel_rim_1350",
  "wheel_rim_1351",
  "wheel_rim_1352",
  "wheel_rim_1353",
  "wheel_rim_1354",
  "wheel_rim_1355",
  "wheel_rim_1356",
  "wheel_rim_1357",
  "wheel_rim_1358",
  "wheel_rim_1359",
  "wheel_rim_1360",
  "wheel_rim_1361",
  "wheel_rim_1362",
  "wheel_rim_1363",
  "wheel_rim_1364",
  "wheel_rim_1365",
  "wheel_rim_1366",
  "wheel_rim_1367",
  "wheel_rim_1368",
  "wheel_rim_1369",
  "wheel_rim_1370",
  "wheel_rim_1371",
  "wheel_rim_1372",
  "wheel_rim_1373",
  "wheel_rim_1375",
  "wheel_rim_1376",
  "wheel_rim_1377",
  "wheel_rim_1378",
  "wheel_rim_1379",
  "wheel_rim_1380",
  "wheel_rim_1381",
  "wheel_rim_1382",
  "wheel_rim_1383",
  "wheel_rim_1384",
  "wheel_rim_1385",
  "wheel_rim_1386",
  "wheel_rim_1387",
  "wheel_rim_1388",
  "wheel_rim_1389",
  "wheel_rim_1390",
  "wheel_rim_1391",
  "wheel_rim_1392",
  "wheel_rim_1393",
  "wheel_rim_1394",
  "wheel_rim_1395",
  "wheel_rim_1396",
  "wheel_rim_1397",
  "wheel_rim_1398",
  "wheel_rim_1399",
  "wheel_rim_1400",
  "wheel_rim_1401",
  "wheel_rim_1402",
  "wheel_rim_1403",
  "wheel_rim_1404",
  "wheel_rim_1405",
  "wheel_rim_1406",
  "wheel_rim_1407",
  "wheel_rim_1408",
  "wheel_rim_1409",
  "wheel_rim_1410",
  "wheel_rim_1411",
  "wheel_rim_1412",
  "wheel_rim_1413",
  "wheel_rim_1414",
  "wheel_rim_1415",
  "wheel_rim_1416",
  "wheel_rim_1417",
  "wheel_rim_1418",
  "wheel_rim_1419",
  "wheel_rim_1420",
  "wheel_rim_1421",
  "wheel_rim_1422",
  "wheel_rim_1423",
  "wheel_rim_1424",
  "wheel_rim_1425",
  "wheel_rim_1426",
  "wheel_rim_1427",
  "wheel_rim_1428",
  "wheel_rim_1429",
  "wheel_rim_1430",
  "wheel_rim_1431",
  "wheel_rim_1432",
  "wheel_rim_1433",
  "wheel_rim_1434",
  "wheel_rim_1435",
  "wheel_rim_1436",
  "wheel_rim_1437",
  "wheel_rim_1438",
  "wheel_rim_1439",
  "wheel_rim_1440",
  "wheel_rim_1441",
  "wheel_rim_1442",
  "wheel_rim_1443",
  "wheel_rim_1444",
  "wheel_rim_1445",
  "wheel_rim_1446",
  "wheel_rim_1447",
  "wheel_rim_1448",
  "wheel_rim_1449",
  "wheel_rim_1450",
  "wheel_rim_1451",
  "wheel_rim_1452",
  "wheel_rim_1453",
  "wheel_rim_1454",
  "wheel_rim_1455",
  "wheel_rim_1456",
  "wheel_rim_1457",
  "wheel_rim_1458",
  "wheel_rim_1459",
  "wheel_rim_1460",
  "wheel_rim_1461",
  "wheel_rim_1462",
  "wheel_rim_1463",
  "wheel_rim_1464",
  "wheel_rim_1465",
  "wheel_rim_1467",
  "wheel_rim_1469",
  "wheel_rim_1473",
  "wheel_rim_1474",
  "wheel_rim_1475",
  "wheel_rim_1476",
  "wheel_rim_1477",
  "wheel_rim_1478",
  "wheel_rim_1479",
  "wheel_rim_1480",
  "wheel_rim_1481",
  "wheel_rim_1482",
  "wheel_rim_1483",
  "wheel_rim_1484",
  "wheel_rim_1485",
  "wheel_rim_1486",
  "wheel_rim_1489",
  "wheel_rim_1490",
  "wheel_rim_1491",
  "wheel_rim_1492",
  "wheel_rim_1493",
  "wheel_rim_1494",
  "wheel_rim_1499",
  "wheel_rim_1500",
  "wheel_rim_1501",
  "wheel_rim_1502",
  "wheel_rim_1503",
  "wheel_rim_1504"
];

export function getNeonKeys(option: string = "all"): { rewards: string[]; carParts: string[] } {
  if (option === "animated") {
    return {
      rewards: ALL_NEON_REWARDS,
      carParts: ALL_NEON_BODY_PARTS.filter(p => p.includes("animated"))
    };
  }
  if (option === "static") {
    return {
      rewards: [],
      carParts: ALL_NEON_BODY_PARTS.filter(p => p.includes("static") || p.includes("empty"))
    };
  }
  if (option === "pulse_flow") {
    const r = ALL_NEON_REWARDS.filter(k => {
      const m = k.match(/\d+/);
      return m && parseInt(m[0], 10) <= 8;
    });
    const c = ALL_NEON_BODY_PARTS.filter(k => {
      const m = k.match(/\d+/);
      return !m || parseInt(m[0], 10) <= 8;
    });
    return { rewards: r, carParts: c };
  }
  if (option === "cyber_hyper") {
    const r = ALL_NEON_REWARDS.filter(k => {
      const m = k.match(/\d+/);
      return m && parseInt(m[0], 10) >= 9;
    });
    const c = ALL_NEON_BODY_PARTS.filter(k => {
      const m = k.match(/\d+/);
      return m && parseInt(m[0], 10) >= 9;
    });
    return { rewards: r, carParts: c };
  }
  return { rewards: ALL_NEON_REWARDS, carParts: ALL_NEON_BODY_PARTS };
}

export function getTireSidewallKeys(option: string = "all"): { rewards: string[]; carParts: string[] } {
  if (option === "racing_drift") {
    const racing = ["faster", "faster_white", "drifthunters", "gripx", "oversteer_1", "oversteer_2", "oversteer_3"];
    const r = ALL_TIRE_SIDE_WALL_REWARDS.filter(k => k.includes("faster") || ["1","2","3","4","6","7"].some(n => k.endsWith("_" + n)));
    const c = ALL_TIRE_SIDE_WALL_CAR_PARTS.filter(p => racing.some(sub => p.includes(sub)));
    return { rewards: r, carParts: c };
  }
  if (option === "street_style") {
    const street = ["shinobi", "toccata", "donuts", "apex_rubber", "yolotire"];
    const r = ALL_TIRE_SIDE_WALL_REWARDS.filter(k => ["8","9","10","11","12","13","14"].some(n => k.endsWith("_" + n)));
    const c = ALL_TIRE_SIDE_WALL_CAR_PARTS.filter(p => street.some(sub => p.includes(sub)));
    return { rewards: r, carParts: c };
  }
  return { rewards: ALL_TIRE_SIDE_WALL_REWARDS, carParts: ALL_TIRE_SIDE_WALL_BODY_PARTS };
}

export function getNumberPlateKeys(option: string = "all"): { rewards: string[]; carParts: string[] } {
  if (option === "events") {
    const eventKeywords = ["halloween", "lunar", "carnival", "snowfest", "championship", "gymkhana", "confrontation", "final_charge"];
    return {
      rewards: ALL_NUMBER_PLATE_REWARDS.filter(k => eventKeywords.some(w => k.toLowerCase().includes(w))),
      carParts: ALL_NUMBER_PLATE_BODY_PARTS.filter(k => eventKeywords.some(w => k.toLowerCase().includes(w)))
    };
  }
  if (option === "jdm_street") {
    const jdmKeywords = ["akuma", "oni", "street", "dr-ft", "boost", "500hp", "456897", "666666", "0000", "2fast4u", "kawa11", "run", "patrol", "blankcat", "own3d"];
    return {
      rewards: ALL_NUMBER_PLATE_REWARDS.filter(k => jdmKeywords.some(w => k.toLowerCase().includes(w))),
      carParts: ALL_NUMBER_PLATE_BODY_PARTS.filter(k => jdmKeywords.some(w => k.toLowerCase().includes(w)))
    };
  }
  return { rewards: ALL_NUMBER_PLATE_REWARDS, carParts: ALL_NUMBER_PLATE_BODY_PARTS };
}

export function getWheelRimKeys(option: string = "all"): { rewards: string[]; carParts: string[] } {
  if (option === "battlepass") {
    return {
      rewards: ALL_WHEEL_RIM_REWARDS,
      carParts: ALL_WHEEL_RIM_BODY_PARTS.filter(k => {
        const m = k.match(/\d+/);
        return m && parseInt(m[0], 10) >= 1379;
      })
    };
  }
  if (option === "aftermarket_jdm") {
    return {
      rewards: [],
      carParts: ALL_WHEEL_RIM_BODY_PARTS.filter(k => {
        const m = k.match(/\d+/);
        return !m || parseInt(m[0], 10) < 1379;
      })
    };
  }
  return { rewards: ALL_WHEEL_RIM_REWARDS, carParts: ALL_WHEEL_RIM_BODY_PARTS };
}
